#######################################
###  My tmux custom configuration   ###
#######################################

#--------------------------------------
#Setting the prefix key
#--------------------------------------
set -g prefix C-a

#--------------------------------------
#Using r to aply the changes
#--------------------------------------
unbind r
bind r source-file ~/.tmux.conf

#--------------------------------------
# Options to make tmux more pleasant
#--------------------------------------
set -g mouse on
set -g default-terminal "tmux-256color"

#---------------------------------------
#Setting up the place for the status bar
#---------------------------------------
set-option -g status-position top

#---------------------------------------
#          List of plugins
#---------------------------------------
set -g @plugin 'tmux-plugins/tpm'               #tmux plugin manager (it's like lazy for tmux)
set -g @plugin 'catppuccin/tmux#v2.1.3'         #catppuccin for tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'    #ressurect saves the environtmet (C-a + C-s)
set -g @plugin 'tmux-plugins/tmux-continuum'    #saves the environment every 15 minutes
set -g @plugin 'christoomey/vim-tmux-navigator' #uses C-(h,j,k,l) as in vim

#---------------------------------------
# Configure tmux-continuum
#---------------------------------------
set -g @continuum-restore on

#---------------------------------------
# Configure the catppuccin plugin
#---------------------------------------
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

#--------------------------------------
# Load catppuccin
#--------------------------------------
run ~/.tmux/plugins/tmux/catppuccin.tmux

#-------------------------------------------------
# Make the status line pretty and add some modules
#-------------------------------------------------
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
